# Generated by Django 3.2.7 on 2022-06-04 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
                ('file_name', models.CharField(max_length=255)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.cleaner')),
            ],
        ),
    ]
