# Generated by Django 3.2.7 on 2022-06-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_cleaneravatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneravatar',
            name='file_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
