# Generated by Django 3.2.7 on 2022-06-05 13:35

from django.db import migrations, models
import hotel_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_cleaneravatar_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[hotel_app.models.FileValidator(content_types=('image/jpeg',), max_size=102400)])),
            ],
        ),
    ]
