# Generated by Django 3.2.7 on 2022-06-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_fileuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaner',
            name='old_phone',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
    ]
