# Generated by Django 3.2.7 on 2022-06-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_cleaner_old_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaner',
            name='old_phone',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
