# Generated by Django 3.2.7 on 2022-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_auto_20220613_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название номера'),
            preserve_default=False,
        ),
    ]
